network:
  version: 2
  ethernets:
    enp1s0f0np0:
      dhcp4: false
      addresses: 
        - x.x.x.x/24
      nameservers:
        addresses: [y.y.y.y]
      routes:
        - to: default
          via: z.z.z.z
